### ISSUE TITLE
Update request: xQc cow ("streamer raid") change/removal

### ISSUE THREAD

**Issue by peepopoggers** [placeAtlas/atlas#1043]
- Summary of changes:
Change the opinionated addition to the cow
![image](https://user-images.githubusercontent.com/72892531/162298213-90af2802-a84c-408a-91c4-e72dab8c057e.png)

The second part of the first sentence seems completely irrelevant and unrelated to the art, and same for the second, which is unrelated to the artwork. As there is already an info box on this area, I do not see the use of this comment, as it does not serve its designated purpose.

**Comment by AnonymousRandomPerson** [comment]
Removed.
