### ISSUE TITLE
Update request: Unnecessary hate and 

### ISSUE THREAD

**Issue by iAlex11** [placeAtlas/atlas#1104]
- Summary of changes:
<img width="305" alt="image" src="https://user-images.githubusercontent.com/28487357/162473014-aff6e5d9-b71e-40cf-8c5b-230750c83aae.png">

The last comment is full of hate and is just unnecessary. It is obvious an FC Barcelona (Real Madrid's biggest rival) fan made it, and since there are no hate comments on the Barcelona drawing, it would be great to have them removed from the Real Madrid drawing as well.

**Comment by nico-abram** [comment]
Hi, could you send a pull request with your changes for us to review and merge?

**Comment by jarp0l** [comment]
Somebody added one for Barcelona as well :rofl: 
https://place-atlas.stefanocoding.me/?id=tx3swr
