### ISSUE TITLE
Update request: Updating description of a mural to be accurate.

### ISSUE THREAD

**Issue by mrkvicka22** [placeAtlas/atlas#1111]
- Summary of changes:
![image](https://user-images.githubusercontent.com/40635376/162494392-25c6fb02-16af-4c16-9f4c-90b83ccbdded.png)

The second description is very inaccurate an there should be this instead:
>A logo of rlgym, a python API to treat the game Rocket League as an OpenAI Gym environment.

A subreddit linked can be `r/RocketLeagueBots` as RLGym does not have their own.
A website should be `https://rlgym.org/`

**Comment by AnonymousRandomPerson** [comment]
Updated.
