### ISSUE TITLE
Netlify preview should link to new diff modes

### ISSUE THREAD

**Issue by memmam** [placeAtlas/atlas#1113]
See issue #1020 and subsequent PR #1068, I don't think the `?mode=diff` and `?mode=diffonly` settings should be secret, because not everyone checking pull requests may know about or know to use them. I think it should be updated to include a link to one of the new modes underneath the main 'deploy preview', or replace the main 'deploy preview' with a `?mode=diff` link.

**Comment by nico-abram** [comment]
See https://github.com/placeAtlas/atlas/pull/1092 , that PR is going to make them visible outside of the live website

**Comment by memmam** [comment]
Ah, sounds good. I'll close this.
