### ISSUE TITLE
Zooming on the canvas with a touchpad on Firefox is very sensitive

### ISSUE THREAD

**Issue by arafatamim** [placeAtlas/atlas#1117]
I can zoom the canvas with my touchpad from max to min zoom with a ~0.5cm swipe. This makes it very difficult to precisely focus on a spot. I've tested the touchpad scroll sensitivity and it's set to a reasonable value, in fact I don't face the same problem on a website like Google Maps.

**Comment by Hans5958** [comment]
Related: #436

**Comment by TrevorSayre** [comment]
Can you give some info about your touchpad? Make and model of the laptop, operating system, etc. I'm curious if your wheel event isn't pixels but rather lines. Pixels is solved, lines is not.

**Comment by arafatamim** [comment]
Ok I've tested it on Firefox where the problem occurs, but scrolling works fine on Chromium browsers.
I'm running Linux (Wayland libinput) on an Ideapad 330.
