### ISSUE TITLE
Change the center algorithm

### ISSUE THREAD

**Issue by fabi321** [placeAtlas/atlas#1178]
The current algorithm for calculating the center of a polygon is only using the "center of mass", also called centroid. However, this sometimes leads to situations in which the center of a polygon is not actually part of the polygon. See [here](https://deploy-preview-1166--place-atlas.netlify.app/?id=000071) or [here](https://deploy-preview-1166--place-atlas.netlify.app/?id=twtqmq).

I thus want to discuss, if we want to switch to another algorithm of calculating the center, by mapbox.
See [here](https://blog.mapbox.com/a-new-algorithm-for-finding-a-visual-center-of-a-polygon-7c77e6492fbc) for an explanation, or in [this repository](https://github.com/mapbox/polylabel) for an implementation.

I'm open to actually implementing the new algorithm if it is wanted.

**Comment by fabi321** [comment]
I can try to implement this.

On the other hand I just realized, that we currently have 2 implementations of the same algorithm, one in format.py and one in draw.js, and we could potentially move the "finding the center" process completely to the backend scripts, eliminating the need for an extra js implementation. This would reduce the amount of maintenance needed.

I'm thus only going to try to implement an python version for now.

**Comment by Hans5958** [comment]
Is CDNs possible? We can straight import https://cdn.jsdelivr.net/npm/polylabel@1.1.0/polylabel.min.js with it.

**Comment by fabi321** [comment]
My thought is that as we run formatter.py on the data anyways, we can also remove this step from the submitting side. The delivered center thus conveys no extra meaning.

About a more time complex algorithm: I have added the mapbox algorithm now, and it already runs considerably longer (6.3s instead of 0.6s on my machine).
Furthermore, I don't think that this extra accuracy is needed in our case.

**Comment by Hans5958** [comment]
Oh, yeah. Silly me for forgetting that formatter would be run every crawl.

**Comment by Hans5958** [comment]
On second thought, I think this would confuse those who wanted to edit, so I think it's best to implement it JS-side.
