### ISSUE TITLE
Project status on categorising problematic symbols/flags

### ISSUE THREAD

**Issue by Zanthed** [placeAtlas/atlas#1211]
Hi! I'm wondering if there's a stance on whether you will be categorising highly problematic/illegal flags and symbols?

There's a certain flag that's categorised on your website that would be better discussed in private due to strange discourse around this flag that would be astroturfed by these people if mentioned publicly.

Is there a way I can contact a project maintainer about this? I have Discord too.

**Comment by Codixer** [comment]
Send me a message on Discord (Stefano#7366)

**Comment by Zanthed** [comment]
Sent from June#1418
