### ISSUE TITLE
Update request: [652, 493 Dr Who]

### ISSUE THREAD

**Issue by sergeikat** [placeAtlas/atlas#1313]
- Summary of changes:
Edit to the description of the Dr Who tiles, currently says: Though it's unclear which regeneration of the Doctor stands in the doorway,
I believe based on the hairstyle attempted, coat colour, but more likely based on the multicoloured dots I assume to be a scarf, that this particular doctor would be the 4th doctor, Tom Baker

**Comment by AnonymousRandomPerson** [comment]
Updated.
