### ISSUE TITLE
The Remaster Plan

### ISSUE THREAD

**Issue by Hans5958** [placeAtlas/atlas#1314]
The remaster is currently underway! New features, new design, new new! 

Have new, ambitious ideas? You are invited! Tell us, or implement in this remaster by creating a PR towards the `remaster` branch. Please do not submit new/edited entries on it.

You can also test the remaster before it goes up. You may found some bugs that we can fix before it's release. In that case, tell it here!

New entries and edits will still be pushed to `master` (via `cleanup`/`reddit`) to be live later, as usual.

**Visit the current state**: https://remaster.place-atlas.stefanocoding.me/

#### Main

- #1149
    - [x] Editing (#708)
    - [x] Past/alternative canvas entries
    - [x] Multi-canvas paths
    - [x] New links format
    - [x] Canvas variations
        - [x] 30-minute r/place canvas
        - [x] The Final Clean canvases and alternatives
        - [x] #1319
- [x] #1320, #1334 
    - See also: https://github.com/placeAtlas/atlas/pull/1334#issuecomment-1107401977

#### Additional

- [x] #1178, #1235
- [x] Add .gitattributes
- [x] Conversion script

#### Additional After Redesign

- [x] #1318
- [x] Add SVG symbol on buttons
- [x] #820
- [x] Change /r/place to r/place
- [x] Some other minor stuff that we haven't put here. ([check the commits of the PR](https://github.com/placeAtlas/atlas/pull/1315/commits))
- [x] Polishing

### Pre-Merge

- [ ] Cleanup
	- [ ] Remove test code
	- [x] Remove beta warning
- [ ] #1317
- [x] Freeze on atlas.json (do not create new entries or make edits)
- [ ] Run formatter
- [x] Final smoke test
	- [x] Website
	- [x] Crawler

### Post-Merge

- [ ] Smoke test after new format entries in
	- [ ] Website
	- [ ] Crawler
- [ ] Deprecate/remove code that supports the old format

**Comment by Hans5958** [comment]
Upon further consideration, I am concluding that the final image is not 23:59:59 GMT. I have changed it into 22:47:35 GMT, assuming that it took https://rplace.space/combined/1649112455.png. I can't find the timestamp before the whiteout, so if anyone can find it (and also share it), I would appreciated it.

**Comment by Hans5958** [comment]
Reddit defauts to 22:47:40.185 GMT (1649112460185), and [someone](https://www.reddit.com/r/place/comments/txvk2d/comment/i3x5o7e/) observes that it the whiteout starts on 22:47:40.18**6** GMT (164911246018**6**). I'm going with this count.

**Comment by fabi321** [comment]
@Hans5958 as you are planning to add a gitattributes anyway, should we also merge #1165 into this branch?

**Comment by Hans5958** [comment]
> @Hans5958 as you are planning to add a gitattributes anyway, should we also merge #1165 into this branch?

Yeah I will try to get .gitattributes first, then I would merge that (To be honest it won't be needed, but better safe and sorry, I guess!)

**Comment by Hans5958** [comment]
Speaking of which, about the new center algorithm.

Good news: You got some mistakes but I have fixed all of them so it works on the website.
Bad news: The JS calculation is a little bit off. The Python script would take it over, but just wanna let you know.

**Comment by Hans5958** [comment]
As a reminder, here is the current format/schema of the Atlas entries.

```json5
{

	"id": "abcdef",
	"name": "Entry Title",
	"description": "A very cool entry right here",

	"links": {
		// If it is empty, it is best to be excluded. It will still work, added or not.

		// links r/subreddit1 and r/subreddit2
		"subreddit": [ "subreddit1", "subreddit2" ],

		// links discord.gg/invitecode1 and discord.gg/invitecode2
		"discord": [ "invitecode1, "invitecode2" ],

		// links Page 1 and Page 2 on wiki (use underscore instead of space to avoid inaccuracy)
		"wiki": [ "Page_1", "Page_2"],

		"website: [ "https://example.com/", "https://example.net/" ],
	},

	// The key is a collection of time ranges, seperated by a comma. 
	// If it is preceeded with a code and a colon e.g. T, it indicates that it is for a canvas variation.
	"center": {
		"0-168, T:0-2, ...": [ 1.5, 1999.5 ]
	},
	"path": {
		"0-168, T:0-2, ...": [
			[ 1.5, 1999.5 ],
			[ 0.5, 1999.5 ],
			[ 0.5, 1998.5 ],
			[ 1.5, 1998.5 ],
			// ...
		]
	},

	// name of redditors, excluding u/, replaces submitted_by
	"contributors": [ "redditor1", "redditor2" ]

}
```

**Comment by Hans5958** [comment]
The migrator script and the crawler should be updated, but I forgot for someone to test the brand-new `merge-out.py`. It supposed to merge all the submissions, edit or new, after checking, of course.

For crawlers, please test both scripts to ensure it works. For this time I need all the generated files (`temp_atlas.json`, `manual_atlas.json`, `read-ids-temp.txt`) so I know if I need to do further adjustments.

**Comment by fabi321** [comment]
about the redditcrawl.py: should there be some kind of (easy) confirmation needed in order to merge an edit? I'm thinking of showing the diff for a single edit submission in a somewhat readable manner, and selecting/rejecting with one key press, to block malicious edits.

**Comment by Hans5958** [comment]
`redditcrawl.py` does not directly add the entries to the `atlas.json`. It puts it into the a temporary file (`temp-atlas.json`), persumably then checked, and then either be merged manually or with the script (`read-ids-temp.txt`). `temp_atlas.json` also made to check errors before merging it to `atlas.json`, if that's possible, that is.

**Comment by Hans5958** [comment]
We decided to split this into two stages, one with the features, and another with the redesign. Edits will be made to reflect this change.

**Comment by Hans5958** [comment]
We're back using 1 stage, edits have been made.

**Comment by Hans5958** [comment]
I think I'm going back to modify the about page when the redesign done.

For now, should all references of "The 2022 /r/place Atlas" be modified to "The 2022 r/place Atlas" or "The 2022 Place Atlas?" The wiki is "The r/place Wiki", so I'm thinking the former.

**Comment by mxdanger** [comment]
Its officially referred to as r/place by Reddit so I think we should go with "The 2022 r/place Atlas".

**Comment by Hans5958** [comment]
I agree. We're going to do it when the redesign is done.

**Comment by Hans5958** [comment]
ICYMI: We're planning to release the remaster on Friday or Saturday this week (that's 13/14 May 2022).

**Comment by Hans5958** [comment]
:tada:

Sorry, I was quite busy. Glad to see it's coming home!
