### ISSUE TITLE
STATUS OF SUBMISSIONS

### ISSUE THREAD

**Issue by Codixer** [placeAtlas/atlas#249]
Due to an **INCREDIBLE** high surge in submissions and the fact we still need to find the final picture before the whitening. 
Some delay will be brough to the project. **Keep in mind, all the work done here. Has to be done manually, so we have to shift through all 181 PR's and submissions by ourselves.**

**Comment by Codixer** [comment]
I'm leaving this issue open for conversation, questions or comments

**Comment by xMatador-Git** [comment]
I pull requested #144 
it has one of the last images before the destruction, or if you are waiting for a clean one with fixed artworks look at the reddit [r/thefinalclean](https://www.reddit.com/r/thefinalclean) they are working on it.

**Comment by enshael** [comment]
Is it possible to rework the entries into individual files and let a pipeline merge them and dynamically add in ids? This will make the conflict resolution step go away.

**Comment by Aikoyori** [comment]
Either that or the one on Wikimedia Commons has more stuff

https://commons.wikimedia.org/wiki/File:RPlace2022.png

**Comment by enshael** [comment]
> Either that or the one on Wikimedia Commons has more stuff
> 
> https://commons.wikimedia.org/wiki/File:RPlace2022.png (it is not)

https://rplace.space/ has the timelapse (with some gaps during expansions). https://rplace.space/raw/ has the images used in the video. the final canvas should be somewhere in there.

**Comment by molleer** [comment]
I am looking through the pull request to see if there are some issues with the submissions.
What I am judging is:
:heavy_check_mark: / :x: Preview runs well
:heavy_check_mark: / :x: Name
:heavy_check_mark: / :x: Description is accurate
:heavy_check_mark: / :x: Website link is related to the artwork
:heavy_check_mark: / :x: Marked area encompasses the artwork
:heavy_check_mark: / :x: Subreddit looks related
:heavy_check_mark: / :x: Code formatting (one line, trailing comma)

**Comment by Nivek770** [comment]
Should commits and pull requests be done directly on master or on github-1? People seem to be doing both

**Comment by DRKSLV** [comment]
> ✔️ / ❌ Marked area encompasses the artwork

Hard to judge when the Canvas is still outdated
I urge you guys to first merge #144, it is extremely close to the final image, so all reddits should be in their final area

We can then move to r/thefinalclean or official images

This would just prevent outdated pull requests!!

**Comment by memmam** [comment]
For some reason the version of the canvas the Atlas is using right now is MUCH older than the version it was using this morning. Regardless, u/ggAlex (Reddit staff) has said that tomorrow a 100% final version of r/Place that's recent up to the very last placed colored pixel will be posted (source: https://www.reddit.com/r/place/comments/tx6rxw/the_second_rplace_atlas_an_interactive_map_with/i3k5pt9/?context=3 )
