### ISSUE TITLE
Feature request: Coordinate display

### ISSUE THREAD

**Issue by SaphireLattice** [placeAtlas/atlas#378]
Gonna put that down in here for the record even though I am gonna work on it (or try to, I'll edit/comment if I can't get it up!)

**Comment by DRKSLV** [comment]
Yea good to have that suggestion here

The project is currently a lil swarmed with pull requests lmao, so it might take a while

**Comment by nico-abram** [comment]
> Gonna put that down in here for the record even though I am gonna work on it (or try to, I'll edit/comment if I can't get it up!)

@SaphireLattice were you able to find time to work on this? Asking in case someone else wants to give it a shot
