### ISSUE TITLE
The zoom is extremely sensitive on OSX

### ISSUE THREAD

**Issue by VictorTaelin** [placeAtlas/atlas#436]
If is very hard to use the site, because any minor zoom using the touchpad on OSX - any Macbook Pro - will zoom all in / all out.

**Comment by funwithtriangles** [comment]
Unfortunately there is no easy way to detect whether a scroll event is coming from a mouse or a trackpad. My advice would be to simply reduce the sensitivity generally, as it's absolutely crazy with a touchpad (testing on Macbook Air M1).

**Comment by ncfavier** [comment]
Using smaller zoom steps would make the website more usable both with a mouse and a touchpad.

**Comment by ThePizzaMuncher** [comment]
The zoom is also _unusably_ sensitive on trackpad.

**Comment by birdbrainswagtrain** [comment]
Reported on the original project here: https://github.com/RolandR/place-atlas/issues/11

Wheel events are a pain and I'm not sure what the best answer is -- taking the sign of the event is a way to fix a lot of inconsistencies and that's what the code already does. https://github.com/Codixer/place-atlas/blob/master/web/_js/main.js#L229-L260

**Comment by Hans5958** [comment]
To be honest I would agree that the steps are too large, even for mouse users, compared to something like Google Maps. Something needs to be done.

**Comment by ThePizzaMuncher** [comment]
That’s fair. What’s also a thing is that normally, pinch gestures on laptops control the browser’s zoom instead of the site’s own; using the scroll gesture instead of the pinch one works just fine.

**Comment by Hans5958** [comment]
My pinch gestures control the site's zoom here

**Comment by ThePizzaMuncher** [comment]
that’s weird; maybe most sites just implement some standard that this doesn’t.

**Comment by ThePizzaMuncher** [comment]
add.: the two‐finger scroll gesture is not, in fact, usable.

It’s usable on phones, which is weird, but on the laptop it’s only better than the pinch gesture because you are only moving one way along one axis.

**Comment by Hans5958** [comment]
I'm using Firefox. You?

**Comment by TrevorSayre** [comment]
It's an issue with inertial/momentum scrolling. Is the `wheel` event for zoom debounced?

**Comment by sbritorodr** [comment]
Actually, there's a clever solution posted in [StackOverflow](https://stackoverflow.com/questions/10744645/detect-touchpad-vs-mouse-in-javascript) about this topic.

It detects the scroll input speed at the first touch "guessing" it's a trackpad and changes the scroll sensibility.

**Comment by ProstoSanja** [comment]
I have the same issue on windows with smooth scrolling enabled (I use MX Master mouse)

**Comment by TrevorSayre** [comment]
My code was merged, so should be fixed on latest master, you can preview here:
https://deploy-preview-896--place-atlas.netlify.app/

Let me know if this doesn't improve your experience and I'll see if I can help make it better.

**Comment by Hans5958** [comment]
Now I think the trackpad is sooo insensitive. Also, is it possible to make this animated zoom on the scroll wheel?

PS. Why it is needed to be differentiated? Just decrease the factor for the scroll and voila

**Comment by TrevorSayre** [comment]
My PR did not affect pinch-to-zoom, only wheel events. It might be worth doing a separate issue for pinch-to-zoom.

**Comment by TrevorSayre** [comment]
Just tested pinch-to-zoom on mobile and it seems totally fine.

**Comment by ProstoSanja** [comment]
This issue was about track pad and smooth scrolling, and it has been addressed in #853 .

Please creat a new one for further zoom problems, and describe them in detail

**Comment by ThePizzaMuncher** [comment]
> Just tested pinch-to-zoom on mobile and it seems totally fine.

It was already totally fine on mobile, at least for me. On Chrome with a touchpad, however, was barely handleable.

**Comment by TrevorSayre** [comment]
@ThePizzaMuncher 
> It was already totally fine on mobile, at least for me. On Chrome with a touchpad, however, was barely handleable.

Agreed, that should now be addressed. Be sure to hard refresh to make sure you're getting the latest.

**Comment by ThePizzaMuncher** [comment]
I’ll check it out, cheers!
