### ISSUE TITLE
Broken Turkish letters

### ISSUE THREAD

**Issue by Orangutanion** [placeAtlas/atlas#627]
![image](https://user-images.githubusercontent.com/64809426/161891979-8184256c-f21a-4560-a981-4f52d92df21b.png)

I'm on Windows and this happens on both Chrome and Firefox. Probably just a font thing.

**Comment by Hans5958** [comment]
Maybe try updating it from https://github.com/dejavu-fonts/dejavu-fonts?

**Comment by Hans5958** [comment]
Got the PR going here. I think it's now good. Check https://deploy-preview-1248--place-atlas.netlify.app/ and tell me if it's now good on yours.
