### ISSUE TITLE
There are 6 entries still using the old id system

### ISSUE THREAD

**Issue by TrevorSayre** [placeAtlas/atlas#817]
<img width="297" alt="image" src="https://user-images.githubusercontent.com/421548/162051051-27f65ebb-5613-42fb-aaca-79ca3e1567e2.png">

"id": 0
"id": 4
"id": 179
"id": 185
"id": 227
"id": 1914

**Comment by ab-gh** [comment]
Thanks for pointing these out - could you open a PR to prepend zeroes to make these 6 chars long?

**Comment by Wayland-Smithy** [comment]
Fixed by #1011 

However there are now some duplicate ids like "000000" and "000179".
There should be no dupes in this regard correct? If so what is the suggested method for dealing with them?
