### ISSUE TITLE
New maps that are much closer to the whiteout

### ISSUE THREAD

**Issue by skellitor301** [placeAtlas/atlas#933]
I've noticed the map used isn't the most last version there is, and I did create a new issue about this but unfortunately I didn't realize it was in the old place atlas and not the 2022 one. [Link to Issue](https://github.com/RolandR/place-atlas/issues/37) Info is all there but I'll share that info here as well

Basically, this is what I can confirm to be as last as you can get with r/place 2022 before the whiteout: https://rplace.space/combined/1649112455.png
I can confirm this because I was actively working on the TotalBiscuit memorial, specifically the left border beside his name. The last bit of work I could do before the whiteout was to start bringing the border along the top and start cutting the Irish flag that was about to invade. You can see this in the linked image as I got one out of the 3 colors before whiteout. This is within 5 minutes of the whiteout.
If you are unsure if I was, here's a link to a post I made roughly an hour to 30 minutes before the whiteout began asking for help and what I was working to make it look like: [Reddit.com/r/Place Link](https://www.reddit.com/r/place/comments/tweil9/totalbiscuit_memorial_spot/)

Unfortunately while that is the last recorded moment that will likely be found, it is not the quality I'm sure you guys want. However, I have found a version that is high quality and is much further along than the current atlas displays. Roughly 30 minutes before the whiteout. https://i.redd.it/ex9g0dctplr81.png

This I'm aware would likely make a bit more work to correct the areas listed in the atlas. I mostly wanted to bring this to the attention of you guys so the atlas could be the most complete it can be.

**Comment by ann4belle** [comment]
#868 resulted in the atlas using the final image recorded by reddit before white-only mode was turned on.

**Comment by TrevorSayre** [comment]
#868 Used the one that was off by 5 pixels. #870 fixes this. So this issue can be closed.
