### ISSUE TITLE
Lots of duplicate or redundant entries

### ISSUE THREAD

**Issue by krikienoid** [placeAtlas/atlas#964]
There are a lot of artwork pieces have multiple submissions for the same piece, there are quite a few pieces that have 2-3 or even more. "Kenny" from South Park, for example is on there 5 times.

<img width="1619" alt="Screen Shot 2022-04-07 at 2 47 27 AM" src="https://user-images.githubusercontent.com/8528227/162137601-8d7d2c3d-b6ed-475b-8e9d-01f228c9baf3.png">

**Comment by ann4belle** [comment]
If you want to help clean these up, you can make a fork of the repo and edit the atlas.json file to remove redundant entries. Then, submit a pull request against the cleanup branch of this repo.
